name: NYC Restaurant Inspection Data Update 

on: 
  workflow_dispatch:
  schedule:
  - cron: "0 17 * * *"
jobs:
    build:
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout repository content
          uses: actions/checkout@v4 #Checkout the repository content to github runner
  
        - name: Setup Python Version
          uses: actions/setup-python@v4
          with:
            python-version: 3.9

        - name: Install Python Packages
          uses: py-actions/py-dependency-install@v4
          with:
            path: "requirements.txt"
          
        - name: Execute Python Script
          env:
            JSON_SECRET: ${{ secrets.JSON_SECRET }}
          run: python data_update.py
